### ISSUE TITLE
when we will have a start doc?

### ISSUE THREAD

**Issue by huang12zheng** [stefanJi/Flutter4GitLab#13]
# What I do:
1.  git clone Flutter4GitLab
2.  modify const.dart
```dart
KEY_ACCESS_TOKEN = 'xxxxxxx';
KEY_HOST = '10.0.2.2'; // 127.0.0.1 is also not work
```
3. flutter run

# What is problem:
console is show (This is taking an unexpectedly long time.) for a long time.

# in a word:
I think you need give a start doc

**Comment by stefanJi** [comment]
Thanks for your advice. 

`KEY_ACCESS_TOKEN` and `KEY_HOST` are keys for store value in local storage. (NSUserDefaults on iOS and SharedPreferences on Android). You should not modify them. 
To config your gitlab token and host, just running this app and you will see config entrance in home page.

**Comment by stefanJi** [comment]
@huang12zheng Doc Updated -> https://github.com/stefanJi/Flutter4GitLab#usage

**Comment by huang12zheng** [comment]
thanks
