### ISSUE TITLE
trouble with gitee

### ISSUE THREAD

**Issue by hdeping** [stefanJi/Flutter4GitLab#24]
I just want to use f4lab to view my own code on gitee.com.
I am using the version of release-v1.1.3 and my config is

<my token>
https://gitee.com
v4

But I ran into a trouble as it shows below:
DioError [DioErrorType.RESPONSE]: Http status error [404]

Does somebody know what happened? I am not sure if  there is something wrong with
my personal access token, I just created in the gitee.

**Comment by stefanJi** [comment]
Thank you for trying F4Lab. But F4Lab only support git repo server base on [GitLab](https://about.gitlab.com/), not support others.

**Comment by hdeping** [comment]
ok,  I will try my own gitlab.  Thanks for your reply.

**Comment by hdeping** [comment]
Is f4lab able for reading source code？

**Comment by stefanJi** [comment]
> Is f4lab able for reading source code？

This feature not developed yet ...

**Comment by hdeping** [comment]
got it.
