### ISSUE TITLE
Can't install release apk

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [stefanJi/Flutter4GitLab#4]
Hey, thanks for the app! I tried installing the release apk, but it stopped at the end. After closing the installer and attempting to install again, it keeps saying install failed. Do you know anything about that? Samsung Galaxy S9+ on Android Pie

**Comment by stefanJi** [comment]
Can you try to install to other devices? I installed it on android pie is no problem.

**Comment by ThinkDigitalRepair** [comment]
I haven't had an opportunity to try yet, sorry
